### ISSUE TITLE
Reflex 배포 테스트

### ISSUE THREAD

**Issue by ryugibo** [pal-ette/iNotePal#40]
[Reflex](https://reflex.dev/docs/hosting/deploy-quick-start/)

https://bit.ly/46Qr3mF

https://inotepal.reflex.run/

**Comment by ryugibo** [comment]
FE 배포는 성공, BE 배포시 DB 마이그레이션이 안돌아서 BE가 안뜸

```bash
2024-04-17 16:58:33.408428 KST | Updating backend...
2024-04-17 16:58:34.302561 KST | Building backend image...
2024-04-17 16:59:12.498842 KST | Updating frontend...
2024-04-17 16:59:13.317909 KST | Frontend updated!
2024-04-17 16:59:13.376555 KST | Deploy success (frontend)
2024-04-17 16:59:40.508216 KST | Deploying backend image...
2024-04-17 16:59:45.362991 KST | Backend updated!
2024-04-17 16:59:45.362997 KST | Deploy success (backend)
Waiting for the new deployment to come up
2024-04-17 17:00:41.616712 KST |  Traceback (most recent call last):
2024-04-17 17:00:41.616713 KST |    File "/home/reflexuser/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1971, in _exec_single_context
2024-04-17 17:00:41.616713 KST |      self.dialect.do_execute(
2024-04-17 17:00:41.616714 KST |    File "/home/reflexuser/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 919, in do_execute
2024-04-17 17:00:41.616714 KST |      cursor.execute(statement, parameters)
2024-04-17 17:00:41.616715 KST |  sqlite3.OperationalError: no such table: user
```

배포 명령어에 db관련 마이그레이션 명령어는 따로 없는걸로 봐선 별도 DB 서버를 두어야 하는듯?

**Comment by ryugibo** [comment]
https://discordapp.com/channels/1029853095527727165/1183929055075123240/1184189119040061592
>  oh I see. In that case, after setting up the reflex.db correctly, when you deploy, add this flag  --upload-db-file to the reflex deploy command. This is a workaround we have for now to include the the sqlite db file until we have a better story on that

**Comment by ryugibo** [comment]
reflex 배포 서비스로는 inference는 불가능한듯, 별도 백엔드 구성하고 프론트엔드는 github pages에 배포하는 방향으로

```python
        print(">>>> BEFORE INFERENCE")
        print(dir(inference_model))
        emote = (
            inference_model.predict(
                inference_model.padding(
                    inference_model.tokenize(
                        [
                            self.question,
                        ],
                    ),
                ),
            ),
        )
        print(">>>> AFTER INFERENCE")
```

```
2024-04-18 13:42:10.064227 KST | rxh-prod-inotepal |  >>>> BEFORE INFERENCE | None | None
2024-04-18 13:42:10.064540 KST | rxh-prod-inotepal |  ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'cache_dir', 'cache_version_dir', 'download_file', 'load_pickle_file', 'model', 'padding', 'paths', 'predict', 'seq_length', 'tokenize', 'tokenizer', 'y_label_binarizer'] | None | None
2024-04-18 13:44:06.789085 KST | rxh-prod-inotepal |  [2024-04-18 04:44:06 +0000] [345] [CRITICAL] WORKER TIMEOUT (pid:352) | None | None
2024-04-18 13:44:06.803104 KST | rxh-prod-inotepal |  [2024-04-18 04:44:06 +0000] [345] [ERROR] Worker (pid:352) was sent SIGABRT! | None | None
```

**Comment by ryugibo** [comment]
배포 완료 되어 테스트 이슈는 종료
